\documentclass[a4paper]{article}

\usepackage{hyperref}

\title{LEA: LEA: An R Package for Landscape and Ecological Association Studies}
\author{Eric Frichot and Olivier Fran\c{c}ois\\
Universite Joseph Fourier Grenoble 1, Centre National de la Recherche Scientifique,\\
TIMC-IMAG UMR 5525, Grenoble, 38042, France.\\
\url{http://http://membres-timc.imag.fr/Olivier.Francois/lea.html}
}
\date{\today}

\begin{document}
\setkeys{Gin}{width=1.0\textwidth}

\maketitle
\section*{Overview}
LEA is an R package dedicated to landscape genomics and
    ecological association tests. LEA can run analyses of population structure
    and genome scans for local adaptation. It includes statistical methods for
    estimating ancestry coefficients from large genotypic matrices and
    evaluating the number of ancestral populations (sNMF, PCA); and identifying
    genetic polymorphisms that exhibit high correlation with some environmental
    gradient or with the variables used as proxies for ecological pressures
    (LFMM), and controlling the false discovery rate. LEA is mainly based on
    optimized C programs that can scale with the dimension of very large data
    sets.

\section{Using LEA in practice}

We illustrate the use of the R package LEA for analyzing ecological genomic data
from simulated populations. After describing 


\subsection{Preparing the data}
Genotypic data must be prepared using the lfmm format (any type of allelic data
is allowed). The LFMM program can handle missing data, but the algorithm used 
for genotype imputation is basic. We encourage users having more than 10% 
missing genotypes in their data to x the missing data issue by using matrix
completion or genotype imputation programs such as IMPUTE2 or MENDEL-IMPUTE
before starting their analyses with LFMM. Ecological data must be prepared 
using the env format. To decide which variables should be used among a large 
number of ecological indicators (eg, climatic variables), we suggest that users
summarize their data using linear combinations of those indicators. Considering
principal component analysis (or similar approaches) and using the first 
components as new ecological variables is one of these approaches.

\subsection{Population structure analysis}

\subsubsection{Principal Component Analysis}

\subsubsection{Inference of individual admixture coefficients}

\end{document}
