######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 22 11:54:50 2012
######################################################################

TEMPLATE = app
TARGET = 
QMAKE_CXXFLAGS = -g 

# Input
HEADERS += aboutdialog.h \
           advancedialog.h \
           datawindow.h \
           newprojectdialog.h \
           newrundialog.h \
           project.h \
           run.h \
           snp.h \
           summarydialog.h \
           summarytable.h \
           zscoredialog.h \
           zscoretable.h \
           lfmmgui.h \
           textwindow.h \
           title.h \
           treewidget.h\
           treeinfo.h
SOURCES += aboutdialog.cpp \
           advancedialog.cpp \
           datawindow.cpp \
           main.cpp \
           newprojectdialog.cpp \
           newrundialog.cpp \
           project.cpp \
           run.cpp \
           summarydialog.cpp \
           summarytable.cpp \
           zscoredialog.cpp \
           zscoretable.cpp \
           lfmmgui.cpp \
           textwindow.cpp \
           treewidget.cpp\
           treeinfo.cpp
RESOURCES += lfmmgui.qrc
