        <header>
        <hgroup>
        <h1> LFMM: Latent Factor Mixed Models </h1>
        <h3> A unified framework for inferring population genetic structure and 
                gene-environment associations </h3>
        </hgroup>
        </header>

        <nav>
        <ul>
            <li><a href="index.htm">Home</a></li>
            <li><a href="news.htm">News</a></li>
            <li><a href="software.htm">Software</a></li>
            <li><a href="tutorial.htm">Tutorial</a></li>
            <li><a href="faq.htm">FAQ</a></li>
            <li><a href="contact.htm">Contact</a></li>
            <li class="pad"></li>
        </ul>
        </nav>

